# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0642865c074923f17fedb8162a62f65fd073e662b8fbf5735c37097e9e5a6bbbb7c2fc25f55c19c85e605cd0fdade1770191e91205da761ce233685d675e324a

test:
  secret_key_base: cd7ad9edfe863143de2f4c50edbd59d1aa1ae3b548548fe7da1159d27805b1e148e65b7f9db5c42ffd605187a56de14fb0cf3575908f36747c6895c4cb6bf561

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
